name = "minimarket-proxy"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Routes - this worker will handle /api/* and /uploads/* requests on your custom domain
routes = [
  { pattern = "plaireplai.com/api/*", zone_name = "plaireplai.com" },
  { pattern = "plaireplai.com/uploads/*", zone_name = "plaireplai.com" },
  { pattern = "www.plaireplai.com/api/*", zone_name = "plaireplai.com" },
  { pattern = "www.plaireplai.com/uploads/*", zone_name = "plaireplai.com" }
]

[vars]
BACKEND_URL = "https://minimarket-f1r5.onrender.com"
